package main

// This file implements the exports defined in wit/world.wit.
// Bindings in the gen/ folder are generated by running: wit-bindgen go
// See README.md for the full build process.

import (
	export_hello_world "hello-world-wasmtime-go-component/guest/gen/export/example/hello/hello-world"
)

// init registers our implementations of the exported WIT functions.
// This is the Go equivalent of `impl Guest for MyComponent` in Rust.
func init() {
	export_hello_world.Exports.Add = add
	export_hello_world.Exports.Greet = greet
}

func add(a int32, b int32) int32 {
	return a + b
}

func greet() {
	println("Hello world!")
}

func main() {}