// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#ifndef __BINDINGS_HELLO_WORLD_H
#define __BINDINGS_HELLO_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Exported Functions from `hello-world`
int32_t exports_hello_world_add(int32_t a, int32_t b);
void exports_hello_world_greet(void);

#ifdef __cplusplus
}
#endif
#endif
